#!/bin/bash
# Bash-lambda disk-based heap

# We need 128 bits of entropy for the heap directory name. This gives us
# guarantees about the soundness of conservative garbage collection ... for the
# rest of the story, see src/gc.

# 128 bits total / 15 bits per random number = 9 numbers
bash_lambda_genkey() { declare i
                       for (( i = 0; i < 9; i += 1 )); do
                         printf '%04x' $RANDOM; done; }

# Is the heap directory set already? If so, then we don't own it, so we won't
# nuke it when the process ends.
[[ -z "$BASH_LAMBDA_HEAP" ]] && declare -r BASH_LAMBDA_OWN_HEAP=yes

# Allow the user to override the heap location if they want to. However, this
# may compromise the effectiveness of conservative GC.
export BASH_LAMBDA_KEY=$(bash_lambda_genkey)
export BASH_LAMBDA_HEAP=${BASH_LAMBDA_HEAP:-${TMPDIR:-/tmp}/blheap-$$-$BASH_LAMBDA_KEY}

if [[ "$BASH_LAMBDA_OWN_HEAP" == yes ]]; then
  mkdir -p "$BASH_LAMBDA_HEAP" || return 1
  ln -s "$BASH_LAMBDA_HEAP" "$BASH_LAMBDA_HEAP/.weak-references"
  date +%s > "$BASH_LAMBDA_HEAP/.last-gc"
fi

bash_lambda_nuke_heap() {
  [[ -e "$BASH_LAMBDA_HEAP/.gc-pid" ]] && kill $(<"$BASH_LAMBDA_HEAP/.gc-pid")
  [[ "${BASH_LAMBDA_HEAP:0:5}" == "/tmp/" ]] && rm -rf "$BASH_LAMBDA_HEAP"; }

[[ "$BASH_LAMBDA_OWN_HEAP" == yes ]] && trap bash_lambda_nuke_heap EXIT
export PATH="$PATH:$BASH_LAMBDA_HEAP"

# Heap allocation
bash_lambda_gensym() { mktemp "$BASH_LAMBDA_HEAP/${1:-gensym}_XXXXXXXXXXXXXX"; }
bash_lambda_gendir() { mktemp -d "$BASH_LAMBDA_HEAP/${1:-gensym}_XXXXXXXXXXX"; }

bash_lambda_sym() { bash_lambda_gc_guard "$(bash_lambda_gensym "$@")"; }
bash_lambda_dir() { bash_lambda_gc_guard "$(bash_lambda_gendir "$@")"; }

bash_lambda_gc_guard() {
  declare file=$1

  # If garbage collection is in-progress, mark the object to prevent it from
  # being collected this time around. We don't mark it as having been visited,
  # however; doing that would cause anything it makes live to be collected
  # erroneously.
  touch "$BASH_LAMBDA_HEAP/.gc-marked-set/${file##*/}" >& /dev/null
  echo "$file"; }

bash_lambda_cons() {
  if [[ $1 == '-n' ]]; then declare file=$BASH_LAMBDA_HEAP/$2
  else                      declare file="$(bash_lambda_gensym $1)"; fi

  cat > $(bash_lambda_gc_guard "$file") &&      # Take everything from stdin
    chmod u+x "$file"                   &&      # All conses are executable
    echo "$file"; }
