#!/bin/bash
# Bash-lambda multimethods

# These work only on fully-named parameters, not on stuff coming from stdin. If
# we can observe the name, then we can extract the type from the beginning of
# the filename. For example:
#
# $ future $f
# /tmp/blheap-xxxx-xxxx/future_xxxxxxxx
# $ ref_type $(future $f)
# future
# $
#
# We then prepend this to the multimethod name to get the specific function
# name:
#
# $ defmulti get
# $ get $(future $f)   -> future_get $(future $f)

bash_lambda_defmulti() {
  declare multi_name=$1
  bash_lambda_defn $1 '$(bash_lambda_ref_type $1)_'$multi_name' "$@"'; }

# Multimethod definitions for bash-lambda functions
# state finished block notify  src/future
# get                          src/future src/atom
# unsafe_get                   src/atom
# count                        src/list src/semaphore
# grab release wrap            src/semaphore src/atom src/pipelock

(declare method
 for method in state finished block notify \
               get \
               unsafe_get \
               count \
               grab release wrap; do
   bash_lambda_defmulti $method; done) > /dev/null
